### PR TITLE
Adding basic functionality for a Launch Pad (awaiting definitive rocket implementation)

### PR DESCRIPTION
**Pull request by xnossisx**
Features in this pull request (at the time of sending):
- A launch pad structure that should permit one fluid input
- Recipe map implementation necessary for the fluid input
- An official language file for GCSB

The launch pad feature needs the following subfeatures before it is ready to merge:
- A legitimate GUI for the controller block
- A rocket loading system
- A fuel loading system
- A controller texture
- Testing

### CODE REVIEW

**Comment by StarL0st** [comment]
Just noting some stuff, I implemented fuel tank and network logic for just basic numbers, still would need to add compat for GT for stuff like water deluge and fuel loading to the rocket

**Comment by StarL0st** [comment]
The RocketEntity class is just a class I stole from zalgo that I am gonna replace when I work on the rocket implementation

**Comment by xnossisx** [comment]
It's probably good enough for what we have ready now.

**Comment by loxoDev** [comment]
I am going to remove the rocketry entity class on a different branch as a heads up. This is because it literally breaks the entire thing lol

**Comment by loxoDev** [comment]
The thing thats breaking it, that is.

**Comment by loxoDev** [comment]
Never mind, this fixes way too many things to do in a seperate PR, merging this now.

**Pull request merged**
